package com.logus.kaizen.model;

public interface TableNames {
	final String UNDERSCORE = "_";
	final String PREFIXO = "KZ";
	final String SECURITY_SCHEMA = "security";
	final String TB_AMBIENTE = PREFIXO + UNDERSCORE + "AMBIENTE";
	final String TB_ATENDIMENTO = PREFIXO + UNDERSCORE + "ATENDIMENTO";
	final String TB_BIBLIOTECA = PREFIXO + UNDERSCORE + "BIBLIOTECA";
	final String TB_CLIENTE = PREFIXO + UNDERSCORE + "CLIENTE";
	final String TB_FUNCAO = PREFIXO + UNDERSCORE + "FUNCAO";
	final String TB_FUNCAO_PASSO_ITEM = PREFIXO + UNDERSCORE + "FUNCAO_PASSO_ITEM";
	final String TB_MONDAI_KEY = PREFIXO + UNDERSCORE + "MONDAI_KEY";
	final String TB_PLANO = PREFIXO + UNDERSCORE + "PLANO";
	final String TB_PLANO_SOLICITACAO = PREFIXO + UNDERSCORE + "PLANO_SOLICITACAO";
	final String TB_PLANO_ITEM_SOLICITACAO = PREFIXO + UNDERSCORE + "PLANO_ITEM_SOLICITACAO";
	final String TB_KOTAE_CONFIG = PREFIXO + UNDERSCORE + "KOTAE_CONFIG";
	final String TB_LIBERACAO = PREFIXO + UNDERSCORE + "LIBERACAO";
	final String TB_PROCESSO = PREFIXO + UNDERSCORE + "PROCESSO";
	final String TB_PASSO = PREFIXO + UNDERSCORE + "PASSO";
	final String TB_PRODUTO = PREFIXO + UNDERSCORE + "PRODUTO";
	final String TB_PROJETO = PREFIXO + UNDERSCORE + "PROJETO";
	final String TB_PAPEL = PREFIXO + UNDERSCORE + "PAPEL";
	final String TB_RESOLUCAO = PREFIXO + UNDERSCORE + "RESOLUCAO";
	final String TB_SOLICITACAO = PREFIXO + UNDERSCORE + "SOLICITACAO";
	final String TB_SOLICITACAO_BIBLIOTECA = PREFIXO + UNDERSCORE + "SOLICITACAO_BIBLIOTECA";
	final String TB_ITEM_SOLICITACAO = PREFIXO + UNDERSCORE + "ITEM_SOLICITACAO";
	final String TB_ITEM_ATENDIMENTO = PREFIXO + UNDERSCORE + "ITEM_ATENDIMENTO";
	final String TB_TIPO_MONDAI = PREFIXO + UNDERSCORE + "TIPO_MONDAI";
	final String TB_TIPO_MONDAI_PROJETO = PREFIXO + UNDERSCORE + "TIPO_MONDAI_PROJETO";
	final String TB_PAPEL_PASSO_ITEM = PREFIXO + UNDERSCORE + "PAPEL_PASSO_ITEM";
	final String TB_TRANSICAO = PREFIXO + UNDERSCORE + "TRANSICAO";
	final String TB_URGENCIA = PREFIXO + UNDERSCORE + "URGENCIA";
	final String TB_COMENTARIO = PREFIXO + UNDERSCORE + "COMENTARIO";
	final String TB_CHRONOS = PREFIXO + UNDERSCORE + "CHRONOS";
	final String TB_ITEM_FUNCAO = PREFIXO + UNDERSCORE + "ITEM_FUNCAO";
	final String TB_ITEM_PAPEL = PREFIXO + UNDERSCORE + "ITEM_PAPEL";
	final String TB_SOLICITACAO_DEPENDENCIA = PREFIXO + UNDERSCORE + "SOLICITACAO_DEPENDENCIA";

	// Auditoria
	final String TB_GRUPO_MUDANCA = PREFIXO + UNDERSCORE + "GRUPO_MUDANCA";
	final String TB_ITEM_MUDANCA = PREFIXO + UNDERSCORE + "ITEM_MUDANCA";

	// SECURITY
	final String TB_USUARIO = SECURITY_SCHEMA + "." + "SEG_USUARIO";
}
